config/routes.rb
Author::Application.routes.draw do
  get "raport/monthlyProjects"
	get "raport/monthlyEmployees"

  resources :departments

  resources :assignments
	root :to => 'raport#monthlyProjects'
 	devise_for :users
  resources :employees
  resources :projects
	match '/welcome', to: 'static_pages#welcome'
	

end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_many :assignments
	has_many :projects, :through => :assignments

  attr_accessible :name, :number, :department_id
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	before_filter :authenticate_user!
  # GET /employees
  # GET /employees.json
	def monthly
		if params[:date] == nil
			@date = Date.current.beginning_of_month
		else
			@date = params[:date]
		end
		@employees = Employee.all
	end

  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
	<div class="field">
    <%= f.label :department %><br />
    <%= f.select :department_id, options_from_collection_for_select(Department.all,"id","name") %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Lista pracowników</h1>

<table>
  <tr>
    <th>imię i nazwisko</th>
    <th>nr marki</th>
		<th>Dział</th>
    <th></th>
		<th></th>
		<th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
		<td><%= employee.name %></td>
    <td><%= employee.number %></td>
    <td><%= Department.find(employee.department_id).name %></td>
    <td><%= link_to 'Pokaż', employee %></td>
    <td><%= link_to 'Edytuj', edit_employee_path(employee) %></td>
    <td><%= link_to 'Usuń', employee, method: :delete, data: { confirm: 'Czy jesteś pewien, że chcesz USUNĄĆ pracownika?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nowy pracownik', new_employee_path %>

app/views/employees/monthly.html.erb
<h1>Zestawienie miesięczne 
<%= date_select "dane", "data", :discard_day => true, :onchange => "this.form.submit();" %>
</h1>
<h1>Dział: </h1>
<table border='0' class="outertable">
  <tr>
    <th>Nazwa</th>
    <th>Numer</th>
    <th>Zadania</th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.name %></td>
    <td><%= employee.number %></td>
<td>
			<table border='0' class="innertable">
  			<tr>
    			<th>Nazwa</th>
    			<th>Pracochłonność</th>
					<th></th>
  			</tr>
					<% employee.assignments.find(:all, :conditions => ["DATE(date) = ?", @date.beginning_of_month]).each do |asgn| %>
						<tr>
							<th><%= Project.find(asgn.project_id).name %></th>
							<th><%= asgn.ManHour %></th>
							<th><%= link_to 'Zmień', edit_assignment_path(asgn, :employee_id => employee.id) %></th>
						</tr>
					<% end %>
			</table>
		</td>
  </tr>
	<tr><td><%= link_to 'Dodaj', new_assignment_path(:employee_id => employee.id) %></td></tr>
<% end %>
</table>
<br />

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>imię i nazwisko:</b>
  <%= @employee.name %>
</p>

<p>
  <b>nr marki:</b>
  <%= @employee.number %>
</p>

<p>
  <b>Dział:</b>
  <%= Department.find(@employee.department_id).name %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>