config/routes.rb
Author::Application.routes.draw do
  get "raport/monthlyProjects"
	get "raport/monthlyEmployees"

  resources :departments

  resources :assignments
	root :to => 'raport#monthlyProjects'
 	devise_for :users
  resources :employees
  resources :projects
	match '/welcome', to: 'static_pages#welcome'
	

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	belongs_to :employee
	belongs_to :project

  attr_accessible :date, :employee_id, :project_id, :ManHour
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
	before_filter :authenticate_user!
  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assignments }
    end
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
    @assignment = Assignment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @assignment }
    end
  end

  # GET /assignments/new
  # GET /assignments/new.json
  def new
    @assignment = Assignment.new
		if params[:employee_id]!=nil then
			@assignment.employee_id = params[:employee_id]
		end
		if params[:project_id]!=nil then
			@assignment.project_id = params[:project_id]
		end
		puts params[:employee_id]
		puts params[:project_id]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @assignment }
    end
  end

  # GET /assignments/1/edit
  def edit
    @assignment = Assignment.find(params[:id])
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(params[:assignment])
		@assignment.date = @assignment.date.beginning_of_month

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render json: @assignment, status: :created, location: @assignment }
      else
        format.html { render action: "new" }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assignments/1
  # PUT /assignments/1.json
  def update
    @assignment = Assignment.find(params[:id])

    respond_to do |format|
      if @assignment.update_attributes(params[:assignment])
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment = Assignment.find(params[:id])
    @assignment.destroy

    respond_to do |format|
      format.html { redirect_to assignments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<% if params[:employee_id]!=nil then %>
	<div class="field">
    <%= f.label "Pracownik:" + Employee.find(params[:employee_id]).name %><br />
  </div>
  <div class="field">
    <%= f.label "Data:" %><br />
    <%= f.date_select :date, discard_day: :true %>
  </div>
	<div class="field">
    <%= f.hidden_field :employee_id %>
  </div>
	<div class="field">
    <%= f.select "project_id", Project.all.collect {|p| [p.name, p.id]}, {:prompt => 'Nazwa projektu'} %>
  </div>
	<div class="field">
    <%= f.label "Pracochłonność:" %><br />
    <%= f.number_field :ManHour %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
	<% end %>
	<% if params[:project_id]!=nil then %>
	<div class="field">
    <%= f.select "employee_id", Employee.all.collect {|e| [e.name, e.id]}, {:prompt => 'Wykonawca'} %>
  </div>
  <div class="field">
    <%= f.label "Data:" %><br />
    <%= f.date_select :date, discard_day: :true %>
  </div>
	<div class="field">
    <%= f.hidden_field :project_id %>
  </div>
	<div class="field">
    <%= f.label "Projekt:", Project.find(params[:project_id]).name %>
  </div>
	<div class="field">
    <%= f.label "Pracochłonność:" %><br />
    <%= f.number_field :ManHour %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
	<% end %>
<% end %>

app/views/assignments/edit.html.erb
<h1>Editing assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<h1>Listing assignments</h1>

<table>
  <tr>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assignments.each do |assignment| %>
  <tr>
    <td><%= assignment.date %></td>
    <td><%= link_to 'Show', assignment %></td>
    <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
    <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Assignment', new_assignment_path %>

app/views/assignments/new.html.erb
<h1>Przyporządkuj zadanie/wkonawcę</h1>

<%= render 'form' %>

<% if params[:source] == "employees" then%>
<%= link_to 'Cofnij', '/raport/monthlyEmployees' %>
<% else %>
<%= link_to 'Cofnij', '/raport/monthlyProjects' %>
<% end %>

app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @assignment.date %>
</p>


<%= link_to 'Edit', edit_assignment_path(@assignment) %> |
<% if params[:source] == "employees" then%>
<%= link_to 'Back', '/raport/monthlyEmployees' %>
<% else %>
<%= link_to 'Back', '/raport/monthlyProjects' %>
<% end %>